(ns tunarr.scheduler.scheduling.strategy
  "Strategy generation and lifecycle management for autonomous programming.

   A strategy is a programming plan generated by the LLM for a specific
   period (monthly or quarterly). It contains high-level theme descriptions,
   per-channel adjustments, and optional special events.

   Strategies are stored in memory and exposed via the HTTP API so that
   Marquee (web frontend) and Hermes can inspect and modify them."

  (:require [clojure.string :as str]
            [cheshire.core :as json]
            [tunarr.scheduler.llm :as llm]
            [taoensso.timbre :as log])
  (:import [java.time ZonedDateTime ZoneId Instant]
           [java.util UUID]))

;; ---------------------------------------------------------------------------
;; Storage
;; ---------------------------------------------------------------------------

(defonce ^:private strategy-store (atom {}))

(defn init
  "Initialise the strategy store.  Returns the store atom."
  []
  (log/info "strategy store initialised")
  strategy-store)

;; ---------------------------------------------------------------------------
;; Helpers
;; ---------------------------------------------------------------------------

(defn- now-iso
  "Current instant as ISO-8601 string."
  []
  (.toString (Instant/now)))

(defn- parse-strategy-response
  "Parse the LLM's JSON response into a structured strategy map."
  [raw-response]
  (try
    (let [content (if (string? raw-response)
                    (get (json/parse-string raw-response true) :content raw-response)
                    (get raw-response :content (str raw-response)))
          ;; The LLM might wrap JSON in markdown code fences
          clean-content (str/replace content #"```json\n?|\n?```" "")
          parsed (json/parse-string clean-content true)]
      (if (map? parsed)
        parsed
        {:error "LLM returned non-JSON" :raw parsed}))
    (catch Exception e
      (log/warn e "Failed to parse strategy response")
      {:error "Parse error" :raw (str raw-response)})))

(defn- make-strategy
  "Create a strategy record from LLM output and metadata."
  [period llm-output channels]
  (let [parsed (parse-strategy-response llm-output)]
    {:id (str (UUID/randomUUID))
     :period period
     :created-at (now-iso)
     :status :draft
     :strategy (:strategy parsed "No strategy generated")
     :channel-adjustments (:channel_adjustments parsed [])
     :special-events (:special_events parsed [])
     :raw parsed
     :channels (mapv (fn [[k _]] (name k)) channels)}))

;; ---------------------------------------------------------------------------
;; Public API
;; ---------------------------------------------------------------------------

(defn generate-strategy!
  "Generate a new strategy via LLM and store it.

   Args:
     llm-config — LLM client config
     channels   — Channel config map
     period     — :monthly or :quarterly

   Returns:
     The generated strategy map."
  [llm-config channels period]
  (log/info "Generating strategy" {:period period})
  (let [channel-names (map (fn [[k _]] (name k)) channels)
        now (str (ZonedDateTime/now (ZoneId/of "UTC")))
        timeframe (case period
                    :monthly "next month"
                    :quarterly "next quarter"
                    "the upcoming period")
        prompt (str "You are a TV programming director. Create a scheduling strategy for "
                    timeframe " starting " now ".\n\n"
                    "Channels: " (str/join ", " channel-names) "\n"
                    "Date: " now "\n\n"
                    "Return a JSON object with exactly these keys:\n"
                    "  strategy: string (brief description of the theme)\n"
                    "  channel_adjustments: array of {channel, theme, notes} objects\n"
                    "  special_events: array of {name, date, description} objects (optional)\n\n"
                    "Rules:\n"
                    "  • Suggest themes that fit the channels' personalities.\n"
                    "  • Special events are optional (empty array if none).\n"
                    "  • Keep channel_adjustments to 1-3 items per channel.\n"
                    "  • Dates should be ISO-8601 strings.")]
    (try
      (let [response (llm/chat-completion!
                       llm-config
                       [{:role "system" :content prompt}
                        {:role "user" :content "Generate strategy"}])
            strategy (make-strategy period response channels)]
        (swap! strategy-store assoc (:id strategy) strategy)
        (log/info "Strategy generated" {:id (:id strategy) :period period})
        strategy)
      (catch Exception e
        (log/error e "Strategy generation failed" {:period period})
        (let [fallback {:id (str (UUID/randomUUID))
                        :period period
                        :created-at (now-iso)
                        :status :draft
                        :strategy "Strategy generation failed"
                        :channel-adjustments []
                        :special-events []
                        :error (.getMessage e)}]
          (swap! strategy-store assoc (:id fallback) fallback)
          fallback)))))

(defn list-strategies
  "Return all strategies sorted newest-first."
  []
  (->> (vals @strategy-store)
       (sort-by :created-at #(compare %2 %1))))

(defn get-strategy
  "Return a single strategy by ID, or nil if not found."
  [id]
  (get @strategy-store id))

(defn apply-strategy!
  "Mark a strategy as applied and trigger any template changes.

   Returns the updated strategy, or nil if not found."
  [id]
  (when-let [s (get-strategy id)]
    (let [updated (assoc s :status :applied :applied-at (now-iso))]
      (swap! strategy-store assoc id updated)
      (log/info "Strategy applied" {:id id})
      updated)))

(defn reject-strategy!
  "Mark a strategy as rejected.

   Returns the updated strategy, or nil if not found."
  [id]
  (when-let [s (get-strategy id)]
    (let [updated (assoc s :status :rejected)]
      (swap! strategy-store assoc id updated)
      (log/info "Strategy rejected" {:id id})
      updated)))

(defn delete-strategy!
  "Remove a strategy from the store.

   Returns the deleted strategy, or nil if not found."
  [id]
  (when-let [s (get-strategy id)]
    (swap! strategy-store dissoc id)
    (log/info "Strategy deleted" {:id id})
    s))

(defn current-strategy
  "Return the most recently created strategy (any period)."
  []
  (first (list-strategies)))

(defn current-strategy-by-period
  "Return the most recent strategy for a given period."
  [period]
  (->> (list-strategies)
       (filter #(= (:period %) period))
       first))
